### ISSUE TITLE
[Question] Should errors be thrown for all response with error codes?

### ISSUE THREAD

**Issue by ram-nad** [octokit/request.js#151]
Some endpoints like ([GET /repos/:owner/:repo/assignees/:assignee](https://developer.github.com/v3/issues/assignees/#check-assignee), used to check if a user can be assigned for an issue) returns `404` code as a valid response to the query.

*Should Octokit throw an error for such responses?*

**Comment by gr2m** [comment]
I want the `@octokit/*` libraries to be consistant/predictable in their behavior. You can think of `@octokit/request` as a primitive, that you can build your higher-level abstraction on which makes your intent more clear, such as 

```js
if (await canUserBeAssignedToIssue(request, { owner, repo, login }) {
  // ...
} else {
  // ...
}
```

The `canUserBeAssignedToIssue` method would catch the error and check if it's a 404, in which case it resolves with false.

If you use [`@octokit/core`](https://github.com/octokit/core.js) or one of the libraries that build upon it, you can create a reusable plugin for cases such as this

**Comment by gr2m** [comment]
I'll close this issue as there is nothing actionable for me, but feel free to continue to comment with follow up questions

**Comment by ram-nad** [comment]
Sir, this is correct. But can we just add a parameter to request constructor, which will stop it from throwing errors in the above cases? (by default, it will throw errors.)

**Comment by gr2m** [comment]
That’s outside of the scope of this library. You can also use @octokit/endpoint and your own request library such as fetch to achieve what you want.
