### ISSUE TITLE
read information from multiple repositories at once

### ISSUE THREAD

**Issue by J-Cake** [octokit/request.js#204]
Fairly novice question, I know, but I've got a list of Repos whose description I'd like to fetch. Currently, I'm reading each one separately, however this takes time. I'm just wondering if / how I could do a batch request to get a list of all repositories I ask for.

Thanks

**Comment by gr2m** [comment]
Do you know the set of repositories you want to load? A GraphQL request is probably your best approach

**Comment by J-Cake** [comment]
I do. I have the names in `User/Repo` format stored in a JSON array

**Comment by gr2m** [comment]
You can construct a GraphQL query that requests the descriptions for all the respositories based on their `User/Repo`:

```graphql
fragment repoProperties on Repository {
  nameWithOwner
  description
}

{
  repo1: repository(owner: "octokit", name: "request.js") {
    ...repoProperties
  }
  repo2: repository(owner: "octokit", name: "graphql.js") {
    ...repoProperties
  }
}
```

You can https://github.com/octokit/graphql.js:


```js
const repositories = [
  { owner: "octokit", repo: "request.js" },
  { owner: "octokit", repo: "graphql.js" },
];

const query = `
fragment repoProperties on Repository {
  nameWithOwner
  description
}

{
  ${repositories
    .map(
      ({ owner, repo }, index) => `repo${
        index + 1
      }: repository(owner: "${owner}", name: "${repo}") {
    ...repoProperties
  }`
    )
    .join("\n")}
}`;

const result = await graphql(query, {
  headers: {
    authorization: `token 7ff04b04e5f4079099f0d589e5afcaf50d73fe59`,
  },
});

console.log(result);
```

**Comment by J-Cake** [comment]
Thanks so much! it worked!!!

**Comment by gr2m** [comment]
Yay, thanks for letting me know!

**Comment by alex-page** [comment]
@gr2m is there a limit for the number of repositories you can hit when doing this approach?

**Comment by gr2m** [comment]
It depends. A graphql query has a cost, based on its complexity. If you get 1500 repos that way without loading any nested information it might work. If it doesn’t you’d boils get an error asking to reduce the complexity.
