### ISSUE TITLE
Get the download URL for a workflow artifact instead of following the redirect and downloading it

### ISSUE THREAD

**Issue by bantic** [octokit/request.js#240]
Is it possible to get the download URL for an artifact?
The [docs here](https://docs.github.com/en/rest/reference/actions#download-an-artifact) suggest that the 302 redirect URL will be returned from a call like this:

```js
let response = await octokit.request('GET /repos/{owner}/{repo}/actions/artifacts/{artifact_id}/{archive_format}', {
  owner: 'octocat',
  repo: 'hello-world',
  artifact_id: 42,
  archive_format: 'archive_format'
})
```

When I am trying that (as well as `octokit.actions.downloadArtifact`, as per [these docs](https://octokit.github.io/rest.js/v18#actions-download-artifact)), it seems that the 302 redirect is followed, making my `response` look like so:

```js
{
  status: 200,
  url: 'https://pipelines.actions...', // <-- this is the correct, signed URL, that I want
  headers: { ... },
  data: ArrayBuffer(23750288) // <-- Downloads the artifact into `data`. I don't want it to do this
}
```

I want to just get that url, without downloading the response into that `data` `ArrayBuffer`.
Is that possible? I've tried adding `request: { redirect: 'manual'}` as an option, but that didn't seem to do it.

**Comment by gr2m** [comment]
In Node.js, yes:


```js
let { url } = await octokit.request('HEAD /repos/{owner}/{repo}/actions/artifacts/{artifact_id}/{archive_format}', {
  owner: 'octocat',
  repo: 'hello-world',
  artifact_id: 42,
  archive_format: 'archive_format'
})
```

In browsers it is not currently possible, due to lacking CORS settings

See also

- https://gr2m.github.io/github-api-wishlist/wishlist/cors-for-adjacent-domains/
- https://gr2m.github.io/github-api-wishlist/wishlist/link-media-type/

**Comment by bantic** [comment]
Thanks for the speedy reply. Fwiw I get a 404 from Github for the `HEAD` request. I might have messed something up with the other headers for the request.

I ended up using Axios (from Node.js), like this:

```js
let request = octokit.actions.downloadArtifact.endpoint({
    owner,
    repo,
    artifact_id,
    archive_format,
  });
  let response = await axios.get(request.url, {
    headers: {
      ...request.headers,
      Authorization: `token ${token}`,
    },
    validateStatus(status) {
      return status === 302;
    },
    maxRedirects: 0,
  });
  let url = response.headers.location;
```

**Comment by gr2m** [comment]
> Fwiw I get a 404 from Github for the HEAD request

I was able to reproduce the problem, thank you! 

That is likely an API bug. The problem is the final URL at `https://pipelines.actions.githubusercontent.com/...`. It does not accept a `HEAD` request.

I'll check in with support and keep you posted. Your workaround looks good for the time being

**Comment by cadesalaberry** [comment]
Thanks @bantic, it is exactly what I was looking for.

**Comment by gr2m** [comment]
For reference, here is a GitHub Action workflow file to create an artifact for testing:

```yml
name: Create artifact
on:
  workflow_dispatch: {}

jobs:
  create-artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: mkdir -p my-artifact

      - run: echo hello > my-artifact/world.txt

      - uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: my-artifact/world.txt
```

See it in action at https://github.com/gr2m/sandbox/actions/workflows/create-artifact.yml

Then I use this script to get the URL, which works

```js
const { Octokit } = require("@octokit/core");

const octokit = new Octokit({
  auth: process.env.GITHUB_TOKEN,
});

run();

async function run() {
  const owner = "gr2m";
  const repo = "sandbox";

  const {
    data: { artifacts },
  } = await octokit.request("GET /repos/{owner}/{repo}/actions/artifacts", {
    owner,
    repo,
  });

  try {
    let { headers } = await octokit.request(
      "HEAD /repos/{owner}/{repo}/actions/artifacts/{artifact_id}/{archive_format}",
      {
        owner,
        repo,
        artifact_id: artifacts[0].id,
        archive_format: "zip",
      }
    );
    console.log(headers.location);
  } catch (error) {
    console.log(error);
  }
}
```

But when I change it to `HEAD /repos/{owner}/{repo}/actions/artifacts` it get a 404. 

But it turns out not to be a problem with the API, the problem is that `octokit` follows the redirect and then retries the `HEAD` request on https://pipelines.actions.githubusercontent.com, which fails.

For node usage, the request can be set to not follow redirects. So this works

```js
let { headers } = await octokit.request(
  "HEAD /repos/{owner}/{repo}/actions/artifacts/{artifact_id}/{archive_format}",
  {
    owner,
    repo,
    artifact_id: artifacts[0].id,
    archive_format: "zip",
    request: {
      redirect: "manual",
    },
  }
);
console.log(headers.location);
```

Note the `request.redirect` option.

Sorry this took me a while to figure out. 

All node-fetch extensions documented [here](https://github.com/node-fetch/node-fetch#options) can be set using `request.[node-fetch extension name]`, but they only work for Node, of course
