### ISSUE TITLE
Node-fetch vulnerability

### ISSUE THREAD

**Issue by GuyKh** [octokit/request.js#260]
Node-fetch vulnerability - as described here:
https://app.snyk.io/vuln/SNYK-JS-NODEFETCH-674311

Suggestion - upgrade to 2.6.1
Following this fix - need to update octokit/rest API as well

**Comment by gr2m** [comment]
Thanks Guy, I missed to bump the minimal required version as part of https://github.com/octokit/request.js/pull/256. Thinking about it, Dependabot should do that, I'll let them know.

I'll fix it manually
