### ISSUE TITLE
Allow data param to accept a readable stream

### ISSUE THREAD

**Issue by swinton** [octokit/request.js#342]
Some endpoints, e.g. [`POST /repos/{owner}/{repo}/git/blobs`](https://docs.github.com/en/free-pro-team@latest/rest/reference/git#create-a-blob), are capable of receiving a large amount of data (I'm unsure of precise limits, but happy to research if it's helpful).

Rather than having to hold all this data in memory, it would nice to just pass in a readable stream, e.g. [via the `data` param](https://github.com/octokit/request.js/blob/e5a3c7466c2c5740770161246b563598e93b2319/README.md#special-cases).

**Comment by gr2m** [comment]
> I'm unsure of precise limits, but happy to research if it's helpful

I think it's 100mb if I recall correctly



> Rather than having to hold all this data in memory, it would nice to just pass in a readable stream, e.g. [via the `data` param](https://github.com/octokit/request.js/blob/e5a3c7466c2c5740770161246b563598e93b2319/README.md#special-cases).

Did you try if it just works? We use `node-fetch` internally, and it seems to support it:
https://github.com/node-fetch/node-fetch#post-data-using-a-file-stream

For special cases when `@octokit/request` is to limited, you can call `request.endpoint(`POST /repos/{owner}/{repo}/git/blobs`, { owner, repo })` to receive generic request option, and pass them into your request library of choice.

**Comment by swinton** [comment]
> We use `node-fetch` internally, and it seems to support it

You're right! It does already work!

Tested with:

```javascript
const fs = require("fs");
const { Readable } = require("stream");
const { request } = require("@octokit/request");

(async () => {
  const data = Readable.from('{"encoding": "utf-8" , "content": "Non-blocking is better than blocking."}');
  const response = await request("POST /repos/swinton/blobs/git/blobs", {
    data,
    headers: {
      authorization: `bearer ${ process.env.GITHUB_TOKEN }`
    }
  });
  console.log(response);
})().catch(console.error);
```

> For special cases when `@octokit/request` is to limited, you can call `request.endpoint(`POST /repos/{owner}/{repo}/git/blobs`, { owner, repo })` to receive generic request option, and pass them into your request library of choice.

TIL! Thanks for the help here :bow:
