### ISSUE TITLE
Exception thrown when using in Electron environments

### ISSUE THREAD

**Issue by swinton** [octokit/request.js#348]
## Background
[Insomnia](https://github.com/Kong/insomnia) is an Electron app for working with APIs. I have a plugin that makes it easier to use GitHub Apps authentication in Insomnia: https://github.com/swinton/insomnia-plugin-github-apps-helper

I recently updated this plugin to use `@octokit/auth-app` instead of `@octokit/app`, since the latter is deprecated: https://github.com/swinton/insomnia-plugin-github-apps-helper/pull/24

As part of this change, I introduced `@octokit/request` as a dependency.

## Issue
I am seeing an error from Insomnia when installing the current version of my plugin:

> Error: Cannot find module '/Users/swinton/Library/Application Support/Insomnia/plugins/insomnia-plugin-github-apps-helper/node_modules/@octokit/request/index.js'. Please verify that the package.json has a valid "main" entry

## Theory
I suspect this may be, since Insomnia is an Electron app, it doesn't know which `dist` to use (`dist-node/`, `dist-web`, ...) in the `@octokit/request` package? 🤷 

## Request
Any guidance on how to get this package working in Electron environments?

**Comment by gr2m** [comment]
Hmm I don't know, I haven't seen this error before. Are you sure it's related to Electron? Do you have any kind of custom build step? Could you try to create a minimal Electron app which only uses `@octokit/request` and nothing else?

**Comment by swinton** [comment]
> Are you sure it's related to Electron?

🤔 It might not be... It could also be an issue with the way Insomnia loads plugins... or could be an issue with my plugin... or with my local setup 😅 

I'll close this for now, as [I have a workaround](https://github.com/swinton/insomnia-plugin-github-apps-helper/pull/25). Thanks for the prompt response, Gregor :bow:
