### ISSUE TITLE
FR: make it possible to distinguish when request has been cancelled (throw special exception?)

### ISSUE THREAD

**Issue by pkrukp** [octokit/request.js#362]
Hi,

Currently, when using `options.request.signal` and `AbortController`, when request is cancelled, a `HttpError` exception is thrown. There is no indication that it was caused by the abort (except for specific `message`).

It would be great if Octokit threw some other exception, for example AbortException/AbortError (not sure if there's a standard for this).

(I was directed here from https://github.com/octokit/rest.js/issues/2036)

Thanks

**Comment by gr2m** [comment]
@pkrukp could you get back to my questions?

> What would the ideal API look like from your perspective? Would you like to start a pull request with a failing test and we discuss the desired API there? Might be easier

No worries if this is no longer relevant to you, just let me know

**Comment by pkrukp** [comment]
Hello, sorry for delayed response. As you said, right now it's not relevant for me - we're still using Octokit but have workarounded lack of separate exception. Unfortunately I'm unable to invest time to improve it.
Thanks for great library anyway :)

**Comment by gr2m** [comment]
no worries. I'll leave the issue open, someone might pick it up eventually, it might be a good addition

**Comment by gr2m** [comment]
@oscard0m are you still looking into this? No pressure, just checking in

**Comment by oscard0m** [comment]
> @oscard0m are you still looking into this? No pressure, just checking in

I was planning to check it but I did not have time, sorry. I just unassigned myself to let this issue free to somebody else with more time. I hope to come back soon 💪🏽

**Comment by mcataford** [comment]
Hi!

I've put together some quick tentative changes to address this in #442, I would love thoughts & feedback if you have any!

**Comment by wolfy1339** [comment]
Since #442 was merged, I believe this can safely be closed as done.
