### ISSUE TITLE
How to list warehouse issues

### ISSUE THREAD

**Issue by awnawnawn** [octokit/request.js#373]
I don't know much about JS. This is my code. I want to `get` the `issues` list of the warehouse
```javascript
<script type="module">
  import {request} from "https://cdn.skypack.dev/@octokit/request";
</script>

<script>
  const listIssue = async () => {
    const result = await request("GET /repos/{owner}/{repo}/issues", {
      owner: "awnawnawn",
      repo: "awnawnawn.github.io",
    });
    console.log(`${result.data.length} repos found.`);
  }

  listIssue();
</script>
```
How should I write it？

**Comment by gr2m** [comment]
Try this

```js
<script type="module">
  import { request } from "https://cdn.skypack.dev/@octokit/request";

  async function listIssue () {
    const result = await request("GET /repos/{owner}/{repo}/issues", {
      owner: "awnawnawn",
      repo: "awnawnawn.github.io",
    });
    console.log(`${result.data.length} issues found.`);
  }

  listIssue();
</script>
```

Note that the response of issues are paginated. You can retrieve up to 100, then you need to paginate. You can use `@octokit/core` with the [pagination plugin](https://github.com/octokit/plugin-rest-endpoint-methods.js/) for that

I'm going to close the issue because there is nothing actionable, but feel free to ask more questions

**Comment by awnawnawn** [comment]
Oh, sorry, my access to the imported module of this CDN is slow, and sometimes it can’t be loaded. Are there other CDN links or other ways to use it?

**Comment by gr2m** [comment]
https://cdn.skypack.dev/@octokit/request is a CDN link. But when you open it also shows you a pinned version for production usage

<img width="1095" alt="image" src="https://user-images.githubusercontent.com/39992/117200639-8dc80280-ada0-11eb-8382-5af5a9bf2cf6.png">

right now that's https://cdn.skypack.dev/pin/@octokit/request@v5.4.15-Rbg0guJIRM1jWyUH1h62/mode=imports,min/optimized/@octokit/request.js. Does that work better for you?

**Comment by awnawnawn** [comment]
The speed is obviously improved. Thank you very much!
