### ISSUE TITLE
pin version of `node-fetch` and add end-to-end test to catch breaking changes

### ISSUE THREAD

**Issue by gr2m** [octokit/request.js#432]
This is in response to https://github.com/node-fetch/node-fetch/issues/1300

**Comment by eamodio** [comment]
Will this be moving to node-fetch 3? Or pinning v2? Hoping for the former. 😄

**Comment by gr2m** [comment]
We’ll probably do both for some time, as we transition to ESM

**Comment by gr2m** [comment]
> We’ll probably do both for some time, as we transition to ESM

we ended up removing the dependency on `node-fetch` altogether via https://github.com/octokit/request.js/issues/432. It will be part of the v7 release. You can pass a custom `fetch` implementation e.g. for older Node versions or for mocking with https://github.com/wheresrhys/fetch-mock
