### ISSUE TITLE
Updating "universal-user-agent" dependency package to version 7.0.0 

### ISSUE THREAD

**Issue by TemRhythm** [octokit/request.js#449]
It's needed to use request on latest macOS Monterey 12

**Comment by wolfy1339** [comment]
That is not possible at this time. `v7` of `universal-user-agent` switches to ESM.

Unfortunately the JS octokit libraries no longer have an active maintainer.

You can read about it in [this discussion](https://github.com/octokit/octokit.js/discussions/620#discussioncomment-1472174), subscribe to it for further updates.

**Comment by daniel-beard** [comment]
Are there any known workarounds for this? I guess I can just fork and republish?

**Comment by wolfy1339** [comment]
Is there any kind of error message, or some message in the console?
It would help me figure out what exactly is going on.

Otherwise, I simply do not see any relevant change in between the versions. Only that the package moved to pure ESM.

**Comment by wolfy1339** [comment]
@TemRhythm @daniel-beard Is this issue still relevant?

If so, can you please respond to the questions I asked in my previous comment

**Comment by wolfy1339** [comment]
@octokit/js-community Is anynyone able to test this?

**Comment by gr2m** [comment]
> It's needed to use request on latest macOS Monterey 12

I have MacOS Montery 12 and `@octokit/request` works just fine for me. We'd need a reproducible test case

**Comment by wolfy1339** [comment]
Closing as we cannot reproduce this issue, and no update for almost a year
