### ISSUE TITLE
request() method not returning any data when getting user repositories

### ISSUE THREAD

**Issue by colias-palaeno** [octokit/request.js#494]
Hi,

I'm having an issue with the `request()` method not returning any data from its promise - it simply returns `[object Promise] { ... }`, with no other information.

On [the README page](https://github.com/octokit/request.js/#request), it states that if the request promise is resolved, an object with 4 keys will be returned, and if the request promise is rejected, an object with 3 keys will be returned - as you can see, I'm getting neither of these.

Please find my code below:

```js
import { Octokit } from "https://cdn.skypack.dev/@octokit/core";

const octokit = new Octokit({
  auth: 'authkey'
});

const req = octokit.request('GET /users/colias-palaeno/repos', {
  username: 'colias-palaeno',
  sort: 'created'
});

async function returnReqData(){
  await req;
  return req.data;
}
  
console.log(returnReqData()); // [object Promise] { ... }
```

**Comment by gr2m** [comment]
The problem with your code is that you don't await the response

Instead of

```js
console.log(returnReqData());
```

Try 

```js
console.log(await returnReqData());
```

or

```js
returnReqData().then(console.log)
```

Here is how you can simplify your code:
https://runkit.com/gr2m/octokit-request-js-494

**Comment by colias-palaeno** [comment]
> The problem with your code is that you don't await the response
> 
> Instead of
> 
> ```js
> console.log(returnReqData());
> ```
> 
> Try
> 
> ```js
> console.log(await returnReqData());

I tried doing that instead, and the console is simply outputting `undefined`. Not sure why

**Comment by gr2m** [comment]
oh sorry I just realized you'll also need to update 

```js
async function returnReqData(){
  await req;
  return req.data;
}
```

to 

```js
async function returnReqData(){
  const { data } await req;
  return data;
}
```

But this code is not very elegant, better look at how I implemented it at https://runkit.com/gr2m/octokit-request-js-494/1.0.0
