### ISSUE TITLE
JWT generated for POST /app/installations/<id>/access_tokens is invalid

### ISSUE THREAD

**Issue by nasirmajid** [octokit/request.js#505]
I am currently trying to use octokit.request to get a file from a github repository (see code below).

```ts
const endpoint = 'GET /repos/{owner}/{repo}/contents/{path}';

    type ContentResponseType = Endpoints[typeof endpoint]['response'];
    const response: ContentResponseType = await octokit.request(endpoint, {
      owner: payload.repository.owner.login,
      repo: payload.repository.name,
      path: 'README.md',

});
```
However, I get an HTTP integration error somewhere in the octokit code.
![image](https://user-images.githubusercontent.com/102952772/184103210-cb56b9c8-79fa-4882-b242-e5ea45d2742e.png)

Upon further inspection and debugging, the issue occurs when making a POST request to the "/app/installations/:id/access_tokens" endpoint and going to the URL https://api.github.com/app/installations/:id/access_tokens gives the message "A JSON web token could not be decoded". This leads me to believe the jwt generated by the octokit code is invalid, and using an online JWT decoder confirms that the signature of the JWT being used is invalid.
Does anyone know why this is happening? I've checked the parameters used to create the jwt (github private key and app id) and they are correct.

**Comment by timrogers** [comment]
Hi @nasirmajid! 👋🏻 Could you please share more of your code, including how you're setting up the `octokit` instance?

**Comment by nasirmajid** [comment]
Absolutely, I am working with a github app that listens to a repo and sends events to a smee instance where we can then retrieve them. The above request occurs within an on-push function in order to be executed every time there is a push event.
     `
   interface GithubConfig {
          privateKey: string;
          appId: number;
          webhookSecret: string;
          clientId: string;
          clientSecret: string;
    }`
    `const githubIntegrationMiddleware = (config: GithubConfig): App => {
          const githubApp = new App({
            appId: config.appId,
            privateKey: config.privateKey,
            webhooks: {
              secret: config.webhookSecret,
            },
            oauth: {
              clientId: config.clientId,
              clientSecret: config.clientSecret,
            },
      });`
    `githubApp.webhooks.on('push', async ({ octokit, payload }) => {
            
        const endpoint = 'GET /repos/{owner}/{repo}/contents/{path}';
             
        type ContentResponseType = Endpoints[typeof endpoint]['response'];
        const response: ContentResponseType = await octokit.request(endpoint, {
          owner: payload.repository.owner.login,
          repo: payload.repository.name,
          path: 'catalog.json',
    
        });
    
        if (response.status !== 200) throw new Error('Reading data failed');
    
        ... (response handling)
`

**Comment by timrogers** [comment]
Thanks! Looking at the code on the GitHub side, I agree with your idea that the JWT seems to be invalid. But I'm not sure why at this point. 

Could you confirm which Octokit package versions you're using (you can check your `package-lock.json`) and what version of Node?

**Comment by nasirmajid** [comment]
I am using the following:
octokit: ^1.8.1,
octokit/types: ^6.37.0,
node: 8.1.2

**Comment by timrogers** [comment]
Are you able to use a newer Node version? I can't be sure that that is the problem, but that is very old and it could be incompatible with the JWT package.

**Comment by wolfy1339** [comment]
We don't even support node versions older than 14 at the moment.

**Comment by timrogers** [comment]
It does look like the `jsonwebtoken` package is at least theoretically compatible with old Node versions, so perhaps that isn't the issue. It just stood out.

Any ideas what else could lead to a corrupted JWT? Perhaps it could be something to do with the formatting of the private key?

**Comment by nasirmajid** [comment]
My bad the node version is "V16.13.2", what I gave you before was the npm version. As for the private key, it is kept in a .env over multiple lines. Could the new line characters be causing an issue?

**Comment by gr2m** [comment]
It's most likely a problem with the private key.

I'd suggest you create a minimal test code using the `App` constructor exported from the `octokit` package. Start out by passing the private key directly as string, to verify that it is valid.

Depending on how you read the `.env` file, multi-line values are supported or not. The latest `dotenv` version does support multi-line values. But I'd check if the value is read out correctly

**Comment by nasirmajid** [comment]
I have tried passing the private key directly as a string and get the same "integration error". The private key is being read correctly from the .env file

**Comment by timrogers** [comment]
How does the JWT look? If you paste it into an online validator, is it readable?

**Comment by nasirmajid** [comment]
Yes, the header and payload are readable but the signature is invalid. When I try to add my private key it says "invalid key, failed to decode"

**Comment by timrogers** [comment]
It sounds like your key might be corrupted in some way.

You could try running this to check it locally if you have `openssl` installed:

```sh
openssl rsa -in PATH_TO_PEM_FILE -pubout -outform DER | openssl sha256 -binary | openssl base64
```

**Comment by nasirmajid** [comment]
I tried creating a new private key (as I don't have access to the pem file of the old one) and ran this command and it was exactly the same as what was shown on github. However using this new private key gives the same integration error.

**Comment by nasirmajid** [comment]
I ended up finding the source of the issue. Essentially the appId wasn't being retrieved from the .env file correctly and so was causing the jwt to be invalid when it was created.
Thanks for the help!
