### ISSUE TITLE
Native Node.js fetch fails with attempting DELETE requests

### ISSUE THREAD

**Issue by rdmurphy** [octokit/request.js#506]
Hello! This possibly overlaps with `@octokit/endpoint` — we noticed today after updating to the latest version of `@octokit/rest` (`v19`) that any API requests that we make that result in a `DELETE` request (in our case it's [delete a label](https://docs.github.com/en/rest/issues/labels#delete-a-label)) now fail when they are ran using Node v18. We think we tracked it down to how `@octokit/request` now opts into using the native Fetch API.

It appears that `node-fetch` and `undici-fetch` (AKA native Node.js fetch) feel differently about `DELETE` requests that set `content-length: 0` (which happens via `@octokit/endpoint`) without adding a `body`. `node-fetch` allows it to happen, `undici-fetch` throws an error with the `UND_ERR_REQ_CONTENT_LENGTH_MISMATCH` code.

**Comment by gr2m** [comment]
> `DELETE` requests that set `content-length: 0`

I don't recall the exact reason, but I remember that there was a weird problem with some of GitHub's REST APIs when the `content-length: 0` header is not set, I'd have to dig for that one a little, or we could run some tests if it's still necessary at all.

**Comment by rdmurphy** [comment]
Forgot to add — I did attempt to hit that `DELETE` endpoint with native Node.js fetch with a bare `fetch()` call (with all the proper headers and authentication) and it _did_ work without the passing of `content-length: 0` or a `body`. Unfortunately did not also attempt to hit `PATCH` and `PUT` endpoints — I saw that`@octokit/endpoint` notes the REST API [does have unique expectations with those](https://github.com/octokit/endpoint.js/blob/8266fc12765e94cb966d5104a375631b4efb0dbf/src/parse.ts#L95-L99).

**Comment by timrogers** [comment]
It looks like this is affecting other places too - see https://github.com/octokit/rest.js/issues/190.

Would it be practical to just set the body to an empty string?

**Comment by gr2m** [comment]
@rdmurphy can you confirm that the problems is resolved for you via `@octokit/endpoint@7.0.2`? Make sure to do a fresh install to get the latest version of `@octokit/endpoint` (`rm -rf package-lock.json node_modules && npm install`)
