### ISSUE TITLE
Automatically retry requests on server errors (502)

### ISSUE THREAD

**Issue by jviotti** [octokit/request.js#52]
I've been recently experiencing 502 server errors from GitHub while using this library. I'm planning to add some retry logic on my application code, but would this make sense as part of this library instead?

**Comment by gr2m** [comment]
We won’t add retry functionality to `@octokit/request` as it’s meant to be as simple as possible, optimized for bundle size.

But you can use `@octokit/rest` and then add the [retry plugin](https://github.com/octokit/plugin-retry.js).
