### ISSUE TITLE
The Fetch API is an experimental feature

### ISSUE THREAD

**Issue by websolutions-hamburg** [octokit/request.js#526]
Is it possible to disable the **ExperimentalWarning** "**The Fetch API is an experimental feature.**" which is displayed since Node.js 18?

Current Node.js: `v18.9.0`

```
(node:6335) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
```

with `--trace-warnings`:
```
(node:73578) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
    at emitExperimentalWarning (node:internal/util:226:11)
    at fetch (node:internal/process/pre_execution:213:5)
    at fetchWrapper (/project/node_modules/@octokit/request/dist-node/index.js:32:10)
    at newApi (/project/node_modules/@octokit/request/dist-node/index.js:152:14)
    at graphql (/project/node_modules/@octokit/graphql/dist-node/index.js:73:10)
    at newApi (/project/node_modules/@octokit/graphql/dist-node/index.js:92:12)

```

**Comment by wolfy1339** [comment]
Unfortunately not.

This is an error given by Node, and not us.

Since Node v18, the fetch API was implemented, and it's still an experimental feature hence the error.

**Comment by websolutions-hamburg** [comment]
Oh ok, so is it correct that you have not changed anything and Node.js 18 has now simply replaced the old fetch function with the new API.

**Comment by wolfy1339** [comment]
That is correct, we haven't changed any code.

There was never a builtin `fetch` function in NodeJS until v18, the `node-fetch` package provided an implementation of that function, and falls back to new builtin `fetch` function on Node v18
