### ISSUE TITLE
[DOCS]: When the native fetch() is used, some options are ignored

### ISSUE THREAD

**Issue by ragrus-nbl** [octokit/request.js#577]
### Describe the need

Hi colleagues!

First of all, thanks for your work!

I wanted to set a proxy for octokit requests and realized that `options.request.agent` (actually, not only this option) is ignored when no custom `fetch` option provided.
If I don't pass a custom fetch, the native one is used which doesn't support a number of parameters described in the docs (README.md).

I believe, there should be some warning in the docs. Another way is to use `node-fetch` by default with a failover to the native `fetch` (also with some note in the docs).

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wolfy1339** [comment]
We have moved away from `node-fetch` to instead rely on the fetch API.

We have cleaned up the documentation to remove options that were only applicable to `node-fetch`.

Because of that, I believe that this issue is resolved
