### ISSUE TITLE
[BUG]: octokit function is due to `repos/.../pulls` internal server error

### ISSUE THREAD

**Issue by yogeshg** [octokit/request.js#589]
### What happened?

We have a script for looking at all commits to generate some release notes. This uses octokit, which is returning following error now. It was last working for me 3 hours ago. It has failed consistently 3 times.

### Versions

 "@octokit/rest": "^18.12.0",

### Relevant log output

```shell
RequestError [HttpError]: Server Error
    at ...@octokit/request/dist-src/fetch-wrapper.js:68:27
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.next (...@octokit/plugin-paginate-rest/dist-src/iterator.js:16:38) {
  status: 502,
  response: {
    url: 'https://api.github.com/repos/wandb/core/pulls?state=closed&direction=desc',
    status: 502,
    headers: {
      connection: 'close',
      'content-length': '32',
      'content-type': 'application/json',
      date: 'Fri, 09 Jun 2023 20:31:20 GMT',
      etag: '"648386be-20"',
      server: 'GitHub.com',
      vary: 'Accept-Encoding, Accept, X-Requested-With',
      'x-github-request-id': '9884:254A:D40D9A8:1B153B64:64838C0D'
    },
    data: { message: 'Server Error' }
  },
  request: {
    method: 'GET',
    url: 'https://api.github.com/repos/wandb/core/pulls?state=closed&direction=desc',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'octokit-rest.js/18.12.0 octokit-core.js/3.6.0 Node.js/16.20.0 (linux; x64)',
      authorization: 'token [REDACTED]'
    },
    request: { hook: [Function: bound bound register] }
  }
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wolfy1339** [comment]
Possibly related to octokit/types.ts#554

**Comment by wolfy1339** [comment]
I don't see why this is a bug on our side. That seems more like a problem on GitHub's side

**Comment by yogeshg** [comment]
Oh, I just assumed you were affiliated to Github. What's the right place for reporting such bugs, could you please help escalate this to Github?

**Comment by wolfy1339** [comment]
I suppose that https://github.com/orgs/community/discussions would be the best place

**Comment by yogeshg** [comment]
Added, Please help increase visibility if you think this issue is real.
https://github.com/orgs/community/discussions/57659
