### ISSUE TITLE
[FEAT]: Allow streaming of the data

### ISSUE THREAD

**Issue by Uzlopak** [octokit/request.js#601]
### Describe the need

Currently octokit/request is not configurable to provide the stream of the response.body. This is an issue, if you want to load the tarball of a project and want to stream it to a tar stream and process the file content on the fly. 

There should be an option, which results in passing the body as stream, so that we can utilitze it if needed.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gr2m** [comment]
For this use case, we recommend you use `@octokit/endpoint` with your own request method. You can access it at `request.endpoint()`

Like this

```js
// https://docs.github.com/en/rest/repos/contents?apiVersion=2022-11-28#download-a-repository-archive-tar
const requestOptions = request.endpoint('GET /repos/{owner}/{repo}/tarball/{ref}', {
  owner: 'OWNER',
  repo: 'REPO',
  ref: 'REF'
})

// {
//   method: 'GET',
//   url: 'https://api.github.com/repos/OWNER/REPO/tarball/REF',
//   headers: {
//     accept: 'application/vnd.github.v3+json',
//     'user-agent': 'octokit-core.js/0.0.0-development Node.js/16.20.1 (darwin; arm64)'
//   },
// }
```

**Comment by Uzlopak** [comment]
Tbh, this doesnt help me. I just used in our bot built in fetch, because there is no benefit in using a package, if I have to set everything manually. The only benefit of using octokit is the potential typesafety. If i have no typesafety then i dont need the package.

**Comment by Uzlopak** [comment]
As i see that you added the "support" tags. If you need support to implement this feature, then could have a look, in providing a PR.

**Comment by gr2m** [comment]
> if I have to set everything manually. The only benefit of using octokit is the potential typesafety. If i have no typesafety then i dont need the package

that's okay, we can't make it work for all possible use cases, everything is a trade off. If this is the only request you need to send, I'd use native fetch, too.

**Comment by Uzlopak** [comment]
Sry but this is not what I expected. I did not expected that my issue gets demoted from feature request to a support request. I expected some feedback regarding the possibility to land this feature and maybe the invitation to provide a PR.

**Comment by gr2m** [comment]
okay if you like to give it a go, you can certainly send a pull request and we can discuss it there. 

Beware that we are currently discussing an introduction of `options.request.fetchOptions` which could be useful in this context.

How do you stream the response with a native fetch currently? Does it work across Node / Browsers / Deno?

**Comment by Uzlopak** [comment]
I checked and i realized that i use node-fetch as our bots use still node 16. 

This is what i do:

```typescript
public processArchive (url: string): Promise<DependabotConfigEntry[]> {
    const headers = {
      Authorization: 'Bearer ' + this.git.octokit.authToken
    }
    return new Promise<DependabotConfigEntry[]>((resolve, reject) => {
      fetch(url, { method: 'GET', headers })
        .then(response => {
          if (!response.ok) {
            throw new Error(`Failed to fetch ${url}. Status: ${response.status}`)
          }

          const tarStream = tarList()
          const uniqueSet: Set<string> = new Set()
          const entries: DependabotConfigEntry[] = []

          tarStream.on('entry', function onentry (entry: ReadEntry) {
            let directory = dirname(entry.path).slice(entry.path.split(sep)[0].length) || sep
            const ecosystem = detectEcosystemByFilepath(basename(entry.path), directory)

            if (ecosystem) {
              // github-actions need to set the path to root
              if (ecosystem === 'github-actions') {
                directory = '/'
              }
              if (uniqueSet.has(ecosystem + '/' + directory) === false) {
                entries.push({
                  'package-ecosystem': ecosystem,
                  directory,
                  schedule: {
                    interval: 'daily'
                  }
                })
                uniqueSet.add(ecosystem + '/' + directory)
              }
            }
          })

          pipeline(response.body, tarStream, error => {
            error
              ? reject(error)
              : resolve(entries)
          })
        })
        .catch(e => {
          reject(e)
        })
    })
  }

```

With this implementation memory spikes and alerts are gone from the gcloud logs.

**Comment by gr2m** [comment]
we cannot rely on `node-fetch` unfortunately, it has some APIs specific to Node. If we consider adding a streaming feature to Octokit, we can only use fetch APIs that are standardized and supported across Node 18+, modern browsers, and Deno.

**Comment by Uzlopak** [comment]
Sure. Issue was that fetch is afaiknot in @types/node and we already used node-fetch in other parts of the code. I would try to provide a solution with native fetch.

**Comment by wolfy1339** [comment]
There is such a thing as read streams with the fetch API

https://developer.mozilla.org/en-US/docs/Web/API/Streams_API/Using_readable_streams

**Comment by wolfy1339** [comment]
This would only require a small modification to the `getResponseData()` function:
https://github.com/octokit/request.js/blob/60e9b5767c18687e479d6c4964055d2757e96cc3/src/fetch-wrapper.ts#L146-L157

Instead of doing anything with `Response.body`, simply return it and that is your stream

**Comment by Uzlopak** [comment]
I created a PR to discuss it further ;)

**Comment by amacneil** [comment]
Glad this was merged! Here's a complete example of streaming release assets from rest.js:

https://github.com/octokit/rest.js/issues/12#issuecomment-1916023479

**Comment by AleksandrHovhannisyan** [comment]
Is there any documentation on this aside from the linked code above? I'm wondering if it's possible to stream the result of `Octokit.issues.listComments`, for example, but I'm not seeing anything in the docs about this.

**Comment by wolfy1339** [comment]
You can stream any request you want. although for pure JSON endpoints like the list comments for issue endpoint. you should be using pagination

You can pass request options to all API methods

**Comment by AleksandrHovhannisyan** [comment]
This is very likely a skill issue on my part as I'm new to HTTP streaming as a concept. I don't want to pollute a closed issue with unnecessary notifications. At the risk of doing that, though, this is what my old code was doing:

```js
const response = await octokit.paginate(octokit.issues.listComments, {
  owner: site.issues.owner,
  repo: site.issues.repo,
  issue_number: issueNumber,
  per_page: 100,
});
```

I tried using the above suggestion of `request: { parseSuccessResponseBody: false }` as well as `octokit.paginate.iterator` [per these docs](https://actions-cool.github.io/octokit-rest/guide/05_pagination/), but neither one seem to give me a readable stream; I always just get `application/json` with an array of all comments at once.

**Comment by wolfy1339** [comment]
Feel free to open a discussion instead. We can carry on there
https://github.com/octokit/octokit.js/discussions
