### ISSUE TITLE
[BUG]: `redirect` option not passed through

### ISSUE THREAD

**Issue by wolfy1339** [octokit/request.js#611]
### What happened?

The `redirect` option is still defined in the types as an option that can be passed, however it isn't getting passed along

### Versions

`@octokit/request` v8

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wolfy1339** [comment]
Is it an error that the types were left in, or is it an error that it isn't passed through

**Comment by gr2m** [comment]
`redirect` is a valid fetch option: 
https://developer.mozilla.org/en-US/docs/Web/API/fetch#redirect

I'd pass it through like signal. There are a few others but I'd wait and see to learn about people's use cases for them. I think most are relevant to browsers only.
