### ISSUE TITLE
Document on how to use the new fetch API equivalent to http agents

### ISSUE THREAD

**Issue by oscard0m** [octokit/request.js#613]
Currently we have a PR in the works, and discussions happening over in the `@octokit/request` repo: https://github.com/octokit/request.js/pull/599

We still need documentation on how to use the new fetch API equivalent to http agents.
If you'd like you can take that up

_Originally posted by @wolfy1339 in https://github.com/octokit/octokit.js/discussions/2484#discussioncomment-6386080_

**Comment by oscard0m** [comment]
I probably will need some guidance here because I don't have experience with `http.Agent`. I created a CodeSandbox code example where we can comment what's the direction to take: https://codesandbox.io/p/sandbox/nifty-stitch-wdlwlf

1. I need to figure out how to test if my overridden `fetch` is being called and its `dispatcher` is working.
2. I'm not sure if this is an option we want to document: https://github.com/nodejs/undici/discussions/2167#discussioncomment-6239992. To me sounds like it would override all the occurrences of `fetch` which is something users may don't want. Is this true?

Node.js GitHub Discussion for more context: https://github.com/nodejs/undici/discussions/2167

Tagging @gr2m because I think you have more context on this.

**Comment by wolfy1339** [comment]
> 1. I need to figure out how to test if my overridden `fetch` is being called and its `dispatcher` is working.

We use that option all the time in the tests, so it works for sure.

You can't use `http.Agent` anymore. you need to use `undici.Agent()`

I'm not sure we really want to document the `dispatcher` option, as it's not standard and only exists for undici...
We recently removed non-standard options that were `node-fetch` only

**Comment by oscard0m** [comment]
> We use that option all the time in the tests, so it works for sure.

👍🏽 
 
> You can't use `http.Agent` anymore. you need to use [`undici.Agent()`](https://undici.nodejs.org/#/docs/api/Agent)

👍🏽 
 
> I'm not sure we really want to document the `dispatcher` option, as it's not standard and only exists for undici... We recently removed non-standard options that were `node-fetch` only

This is what @gr2m posted:
> Add documentation how to create a custom fetch function with a dispatcher preset (it's easy, https://github.com/nodejs/undici/discussions/2167)

I updated the CodeSandbox example with an example with `undici` + `dispatcher` but let me know if that would be what we want to document or just link to undici's docs and that's it.

**Comment by gr2m** [comment]
Codesandbox example looks good, thank you! I _think_ we don't need to import fetch from `undici`, but probably it's a good idea to make sure the `fetch` and `Agent` implementation is on par.

I would create `myFetch` outside of the `request` call, and then set `fetch: myFetch`. That will make it more readable. Other than that I think that's great for a starting point, let's see what people say that try to use it.

**Comment by wolfy1339** [comment]
>  I _think_ we don't need to import fetch from `undici`, but probably it's a good idea to make sure the `fetch` and `Agent` implementation is on par.

The standard fetch types that typescript uses doesn't include the `dispatcher` option. We have to explicitly import `fetch`, and `Agent` in order for it to be proper types.

`Agent` is not even included in NodeJS, it's only part of `undici`. Only `fetch` is exposed as a global/
https://nodejs.org/api/globals.html#fetch
