### ISSUE TITLE
potential bug:  native fetch not throwing errors?

### ISSUE THREAD

**Issue by Uzlopak** [octokit/request.js#699]
I have a bug in the production where a 404 response is not throwing accordingly. 

Very strange behaviour. For this I am currently proposing PRs which make it easier for me to investigate the bug. I have the strong feeling that there is a bug in this repo, and it is not showing properly because we mock the fetch calls.

**Comment by gr2m** [comment]
> I have a bug in the production where a 404 response is not throwing accordingly.

Is your code using vanilla `@octokit/core` or some higher level library? 

is it for an installation access token? I think `@auth/app-token` does retry 404s due to a possible replication lag

**Comment by Uzlopak** [comment]
Maybe something wrong with google cloud functions framework.

**Comment by Uzlopak** [comment]
Somewhere in our code, it seems that the status code of the Response object is a string! Atleast when we use GCF. Very strange

**Comment by gr2m** [comment]
maybe GCF middleware is doing something weird?

**Comment by Uzlopak** [comment]
I focus on improving probot and octokit. maybe then I figure out where the issue is.
